# Generated by Django 4.2.2 on 2023-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
